#!/bin/bash

# Greenbutton provides electical usage in Watt hours https://www.naesb.org//misc/espi.xsd

echo -n "Account #: "
read ACCOUNT

echo -n "Username: "
read USER

echo -n "Password: "
read -s PASS

TODAY=$(date +"%Y-%m-%dT%H:%M:%S")
YESTERDAY=$(date -v-1d +"%Y-%m-%dT%H:%M:%S")

curl --user "$USER:$PASS" "https://api.greenmountainpower.com/api/v2/usage/"$ACCOUNT"/download?startDate="$YESTERDAY"-04:00&endDate="$TODAY"-04:00&format=xml" > data.xml

cat data.xml | xpath '/feed/entry/content/espi:IntervalBlock/espi:IntervalReading[last()]/espi:value/text()'
